const papers = [
  {
    "Paper No.": "1",
    "Subject": "Microeconomics / Teória a aplikácie mikroekonómie v podnikoch",
    "Teacher": "Peter Markovic",
    "Title": "Microeconomic efficiency of individualised human resource development in small and medium-sized enterprises – a systematic literature review",
    "Abstract": "This systematic literature review examines the microeconomic efficiency of individualised personnel development measures in small and medium-sized enterprises (SMEs) in comparison to standardised approaches, with a focus on ROI, productivity and cost-benefit ratios. Scopus and Web of Science were searched according to PRISMA guidelines (2020). Of the 543 studies identified, 11 studies were included after screening. Due to the heterogeneity of the studies, a narrative synthesis was performed. The results showed that 11 studies (2016–2024; countries: UK, Portugal, India, etc.) provide limited but positive evidence. Individualised personnel development increases productivity by 20–67% (7 studies), ROI to 2.3–5.55 (2 studies) and turnover/profit by 6–25% (several). Adaptive e-learning and coaching outperform standard programmes, especially in resource-poor SMEs (evidence quality: moderate). This shows that individualised personnel development approaches can improve microeconomic efficiency in SMEs, but there are significant gaps in comparisons and long-term data.",
    "My role": "Author",
    "Proposal": "Done",
    "written": "Done",
    "defence": "Done",
    "Grade": "A",
    "Published to": "Mr. Markovics publications",
    "at": null,
    "in": null,
    "Conference/Journal": null,
    "ETCS": "C, domestic",
    "Remarks": "Asking Mr. Markovic for current status",
    "Publishing date": null,
    "Link": null
  },
  {
    "Paper No.": "2",
    "Subject": "Current Topics in Management / Súčasné témy v manažmente",
    "Teacher": "Zuzana Skorkova",
    "Title": "Decentralization of Personnel Development in SMEs: Organizational Agility through Individualized Competence Development with Decentralized Multipliers – A Bibliometric Analysis",
    "Abstract": "Small and medium-sized enterprises (SMEs) are under pressure to respond agilely to market changes whilst developing the skills of their employees and managers in an even more targeted and personalised manner. Traditional, centralised human resources development (HRD) structures are increasingly proving too inflexible to meet these requirements. This paper examines the extent to which the decentralisation of HRD responsibilities from central HR departments to decentralised multipliers such as line managers and team leaders offers SMEs advantages in terms of organisational agility and individual skills development. Based on a systematic literature review and bibliometric analysis, using the Bibliometrix R-package, of 628 documents from the Web of Science between 2016–2026, this study identifies the intellectual structure, thematic development and key research clusters in this field. The research is predominantly shaped by authors from China, the UK, Slovakia and other European countries. Despite the high relevance of agility and performance enhancement in SMEs, the explicit link between decentralised HRD, line manager empowerment and individualised competence development remains underrepresented. The analysis suggests that decentralised HRD approaches, when supported by capable multipliers and a conducive learning environment, can significantly improve the organisation’s responsiveness and enables work-integrated competence development. The study also identifies research gaps, particularly regarding empirical impact analyses of decentralised HRD approaches on organisational agility and productivity in SMEs. The findings contribute to the theoretical understanding of agile human resource management in SMEs and provide practical implications for organisational structures seeking to replace standardised training formats with individualised development and career paths.",
    "My role": "Author",
    "Proposal": "Done",
    "written": "Done",
    "defence": "Done",
    "Grade": "A",
    "Published to": "www.kub.edu.al",
    "at": "2026-06-05",
    "in": "12th International Scientific Conference",
    "Conference/Journal": "Conference Proceedings",
    "ETCS": "C, foreign",
    "Remarks": "Completely done and presented, was a first try how a conference works, no ABDC-list, Clear C-Rating",
    "Publishing date": null,
    "Link": null
  },
  {
    "Paper No.": "3",
    "Subject": "Scientific Research / Súčasné témy v manažmente",
    "Teacher": "Peter Markovic",
    "Title": null,
    "Abstract": null,
    "My role": null,
    "Proposal": null,
    "written": null,
    "defence": "Done",
    "Grade": "A",
    "Published to": null,
    "at": null,
    "in": null,
    "Conference/Journal": null,
    "ETCS": null,
    "Remarks": null,
    "Publishing date": null,
    "Link": null
  },
  {
    "Paper No.": "4",
    "Subject": "Informationsystems / Informačné systémy v manažmente",
    "Teacher": "Robert Hanak",
    "Title": "Empowering SMEs: AI and Digital Technologies for individualised and decentralised Human Resource Development – A Systematic Bibliometric Review",
    "Abstract": "Small and medium-sized enterprises (SMEs) face challenges in human resource development (HRD), where individualized and decentralized approaches can be supported by artificial intelligence (AI) and digital technologies. This systematic bibliometric review using Bibliometrix and RStudio analyzes 116 documents from Scopus and Web of Science (1998-2025) to identify trends, clusters, and gaps in the field. With Bibliometrix, keyword networks (dominance of \"artificial intelligence\" and \"skills development\") and motor topics: HRM; Emerging: AI/ML, analyzed. Results show an existing field of individualized and personalized learning systems, but gaps in global collaboration, no specific approaches for SMEs, as well as no implicit approaches in the individualization of HR approaches to increase productivity, which can lead to an empowerment of SMEs. Future research should create more in-depth models for decentralisation and individualisation in the HRD sector as well as SME-specific models.",
    "My role": "Author",
    "Proposal": "Done",
    "written": "Done",
    "defence": "Done",
    "Grade": "A",
    "Published to": "www.sze.hu",
    "at": "2026-09-28",
    "in": "Kautz Conference Györ - Hungary",
    "Conference/Journal": null,
    "ETCS": "C, foreign",
    "Remarks": "Think of revising because its not listed in ABDC-list and publish at another conference, currently C-Rating",
    "Publishing date": null,
    "Link": null
  },
  {
    "Paper No.": "5",
    "Subject": "Financial Strategies / Finančná stratégia a finančné rozhodovanie",
    "Teacher": "Peter Markovic",
    "Title": "Financial decision-making under uncertainty in SMEs: The role of decentralized employee development in reducing managerial risk",
    "Abstract": "This paper examines how decentralized employee development can improve financial decision-making under uncertainty in small and medium-sized enterprises (SMEs). Based on a systematic analysis of 39 scientific sources published between 2010 and 2025, three research areas are integrated: financial decision-making under uncertainty, decentralized HR development and employee empowerment, and financial literacy. The findings indicate that financial literacy, subjective risk intelligence, employee empowerment, and high-involvement work practices can strengthen decision-making quality, organizational resilience, and agility. The study identifies a shift from centralized toward decentralized HR approaches and from individual toward organizational financial literacy. However, the direct relationship between decentralized competence development and financial decision quality remains insufficiently investigated. An integrative theoretical framework is therefore proposed, linking individualized competence development, knowledge and responsibility distribution, financial self-efficacy, and organizational learning to improved financial decision-making and reduced managerial risk in SMEs.",
    "My role": "Author",
    "Proposal": "Done",
    "written": "Done",
    "defence": "Done",
    "Grade": "A",
    "Published to": null,
    "at": null,
    "in": null,
    "Conference/Journal": null,
    "ETCS": null,
    "Remarks": "In discussion with Mr. Markovic where to publish --> Should be B-Rating",
    "Publishing date": null,
    "Link": null
  },
  {
    "Paper No.": "6",
    "Subject": null,
    "Teacher": null,
    "Title": "The overruling of the Chevron doctrine and its ramifications regarding the structure and significance of the federal bureaucracy",
    "Abstract": "The U.S. Supreme Court's decision in Loper Bright Enterprises v. Raimondo (2024) marks a significant shift in administrative law by overturning the Chevron doctrine, which had long granted judicial deference to agency interpretations of ambiguous statutes. In this paper, the legal, political, and practical implications of the ruling will be discussed as it may help rebalance the administrative state, refocus the separation between powers, and strike a balance of power among legislative branches. It discusses the implications of a more aggressive judicial review of agency decisions and the political implications of restricting the authority of unelected bureaucrats. Long-term effects of administrative law and governance under Loper Bright are also described in the paper, with an emphasis on judicial review. Eventually, the case of Loper Bright can be seen as one of the seminal cases in the field of administrative law that can transform the regulatory environment and the nature of government interactions.",
    "My role": "Co-Author",
    "Proposal": null,
    "written": null,
    "defence": null,
    "Grade": null,
    "Published to": null,
    "at": null,
    "in": null,
    "Conference/Journal": "Journal",
    "ETCS": "B, foreign",
    "Remarks": "Will be Scopus listed, clear B-Rating",
    "Publishing date": null,
    "Link": null
  },
  {
    "Paper No.": "7",
    "Subject": "Financial Strategies / Finančná stratégia a finančné rozhodovanie",
    "Teacher": "Peter Markovic",
    "Title": "Digital Maturity and IT Infrastructure Readiness as Preconditions for OKR Software Integration: A Conceptual Framework for Hierarchical Manufacturing Organizations",
    "Abstract": "This study examines how hierarchically structured production and manufacturing companies use agile management approaches such as Objectives and Key Results (OKR) to connect strategic objectives with operational production processes. The technical implementation and integration of OKR software is often a major challenge for process-oriented manufacturing companies. This challenge is particularly evident in companies with established IT structures and outdated ERP systems. Against this background, the study analyzes how the digital maturity level and IT infrastructure of manufacturing companies influence the successful introduction and integration of OKR software into existing information systems. Based on established models and concepts for assessing digital maturity and IT readiness, including Industry 4.0 maturity models and the Capability Maturity Model Integration (CMMI), the thesis examines the relationship between digital competencies and the integration of OKR software into existing IT landscapes. Previous research shows that digital maturity is largely shaped by factors such as technological equipment, data use, organizational culture, and process control. At the same time, digital tools influence integration into existing systems. The study fills existing research gaps by analyzing how different IT architectures, system configurations, and digital maturity levels influence integration issues when implementing OKR software. The results are a conceptual framework for combining digital maturity and IT readiness with the success of the OKR implementation. In addition, practical recommendations for action are created to assess IT readiness, which fit the gradual introduction of OKRs with a focus on the digital development status of a production and manufacturing company in medium-sized companies.",
    "My role": "Co-Author",
    "Proposal": null,
    "written": null,
    "defence": null,
    "Grade": null,
    "Published to": null,
    "at": null,
    "in": null,
    "Conference/Journal": null,
    "ETCS": null,
    "Remarks": "in discussion with Daniel Pfennig",
    "Publishing date": null,
    "Link": null
  },
  {
    "Paper No.": "8",
    "Subject": "Microeconomics / Teória a aplikácie mikroekonómie v podnikoch",
    "Teacher": "Peter Markovic",
    "Title": "Agility and Economic Performance in Small and Medium Enterprises: A Bibliometric Review",
    "Abstract": "Our study presents a bibliometric analysis focused on the relationship between agility and economic performance in small and medium-sized enterprises (SMEs). The main objective is to collect and evaluate bibliometric data on authors, affiliations, publication sources, citations, keywords, research trends and potential future research areas. The analysis is based on a sample of 134 papers published between 2005 and 2025 from the Web of Science database, within the Web of Science categories Management and Business. Data processing and visualization were performed in Biblioshiny (RStudio). The results show that this research area is highly active, rapidly developing and strongly interconnected at a global level. We also note a high degree of international collaboration. The thematic map shows that agility research in SMEs primarily focuses on the interrelationship between performance, capabilities and technology. Our study confirms the multidisciplinary nature of agility research, which integrates technology, strategy, and management to better understand the factors affecting an organizational performance.",
    "My role": "Co-Author",
    "Proposal": null,
    "written": null,
    "defence": null,
    "Grade": null,
    "Published to": "https://dokbat.utb.cz",
    "at": "2026-09-08",
    "in": "Docbat Zlin, CZ",
    "Conference/Journal": "Journal",
    "ETCS": "B, foreign",
    "Remarks": "Will be published Web of Science, B-Rating",
    "Publishing date": null,
    "Link": null
  },
  {
    "Paper No.": "9",
    "Subject": "People & culture / Ľudia a kultúra podniku",
    "Teacher": "Jana Blštáková",
    "Title": null,
    "Abstract": null,
    "My role": null,
    "Proposal": null,
    "written": null,
    "defence": null,
    "Grade": null,
    "Published to": null,
    "at": null,
    "in": null,
    "Conference/Journal": null,
    "ETCS": null,
    "Remarks": null,
    "Publishing date": null,
    "Link": null
  }
];
